/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package construnctor_inheritance;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        //Car myCar = new Car();
        //System.out.println(myCar != null);

        SportCar sc = new SportCar("ferari");
        System.out.println(sc != null);
    }
}
