/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ac.kr.gwnu.com;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        AirForce f15 = new Fighter(5);
        f15.attack();

        AirForce b29 = new Bomber(5);
        b29.attack();

        AirForce lf59 = new LazerFighter(5);
        lf59.attack();
    }
}
