/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.ac.gwnu.com.command;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Lamp lamp = new Lamp("1번 램프");
        Fan fan = new Fan("1번 선풍기");
        LampOnCommand lon1 = new LampOnCommand(lamp);
        LampOffCommand loff1 = new LampOffCommand(lamp);
        FanOnCommand fon1 = new FanOnCommand(fan);
        FanOffCommand foff1 = new FanOffCommand(fan);

        JobQueue jobQueue = new JobQueue();

        jobQueue.add(lon1);
        jobQueue.add(fon1);
        jobQueue.add(foff1);
        jobQueue.add(loff1);

        jobQueue.execute();
        jobQueue.removeAll();
        jobQueue.execute(); // 실행이 아무것도 안됨

        jobQueue.add(fon1);
        jobQueue.add(lon1);
        jobQueue.add(foff1);
        jobQueue.add(loff1);

        jobQueue.execute();
    }
}
