/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello_world;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        int x = 11, y = 55;
        System.out.println("(" + x + y + ")");
    }
}
