/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.ac.gwnu.com.proxy;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        ImageServer imageServer = new ProxyImageServer();
        imageServer.display("a.jpg");
        imageServer.display("b.jpg");
        System.out.println("");
        imageServer.display("a.jpg");
        imageServer.display("b.jpg");
    }
}
