/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.ac.gwnu.com.decorator;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        StringDisplay sd = new StringDisplay("Hello Decorator");
        sd.display();
        System.out.println();

        UnderLineDisplay uld = new UnderLineDisplay(sd, '*');
        uld.display();
        System.out.println();

        BorderDisplay bd = new BorderDisplay(sd, '*');
        bd.display();
        System.out.println();
    }
}
