/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.ac.gwnu.com.fm;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        AirForceFactory boeing = new Boeing();
        AirForceFactory md = new MD();

        WarManager wm = new WarManager(md, boeing);
        wm.attack();
    }
}
