/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.ac.gwnu.com.singleton;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Printer printer = Printer.getInstance();
        printer.print("Hello World");
    }
}
