/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.ac.gwnu.com.bridge;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Weapon sword = new Sword();
        Weapon bow = new Bow();

        Warrior warrior = new Warrior();
        Smith smith = new Smith();

        warrior.setWeapon(sword);
        warrior.handle();

        smith.setWeapon(sword);
        smith.handle();
    }
}
