/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance_composition;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Car myCar = new Car("Sonata");
        myCar.start();
        myCar.radioOn();
        myCar.radioOff();
        myCar.stop();
    }
}
